### PR TITLE
Initial checksums for Repro-CI :)

### PR DESCRIPTION
**Pull request by anton-seaice**
Remove dependency on hh5 environment per https://github.com/COSIMA/access-om3/issues/229 and as implemented through https://github.com/COSIMA/om3-scripts/pull/37

Add initial checksums for repro-CI (from _Generate Initial Checksums_ workflow - https://github.com/ACCESS-NRI/access-om3-configs/actions/runs/11431052215)

This allows running of automated config tests and reproducability CI - see example at https://github.com/ACCESS-NRI/access-om3-configs/pull/145#issuecomment-2425446142

Contributes to https://github.com/COSIMA/access-om3/issues/41

### CODE REVIEW

**Comment by anton-seaice** [comment]
@minghangli-uni - Can you review please ? :)

**Review by CodeGat — APPROVED** [review]

**Review by minghangli-uni — APPROVED** [review]
Thanks @anton-seaice . It looks good to me.

**Comment by anton-seaice** [comment]
!cherry-pick f6046d889986d2b655ea0a7e5a7318d939cb2dda into dev-1deg_jra55do_iaf

**Comment by anton-seaice** [comment]
!cherry-pick f6046d889986d2b655ea0a7e5a7318d939cb2dda into dev-1deg_jra55do_ryf_wombatlite

**Comment by anton-seaice** [comment]
!cherry-pick f6046d889986d2b655ea0a7e5a7318d939cb2dda into dev-025deg_jra55do_ryf

**Pull request merged**
