### PR TITLE
fix JRA55do inputs

### PR DESCRIPTION
**Pull request by aekiss**
This PR replaces https://github.com/ACCESS-NRI/access-om3-configs/pull/113.

When cherry-picked to other branches, this will addresses
https://github.com/COSIMA/access-om3/issues/208
https://github.com/COSIMA/om3-scripts/issues/27
https://github.com/COSIMA/om3-scripts/issues/29

Separate commits  are used to facilitate the differing PRs needed for different configs (e.g. IAF).

### CODE REVIEW

**Comment by aekiss** [comment]
Oops, I should've used `/g/data/vk83/configurations` instead of `/g/data/vk83/experiments`. I'll fix it.

**Review by ezhilsabareesh8 — COMMENTED** [review]
Thanks @aekiss, it looks good to me and it is running. I changed the data mode in the code [refer here](https://github.com/COSIMA/access-om3/commit/96f91599f746b4866bbd3f05ee6eb192ba70d391), we also need to change the executable and the data mode in [datm_in](https://github.dev/ACCESS-NRI/access-om3-configs/blob/c146809cb96eadc2ef01aad87dfb4ca5c554b599/datm_in#L2).

**Comment by aekiss** [comment]
Thanks @ezhilsabareesh8 has https://github.com/COSIMA/access-om3/commit/96f91599f746b4866bbd3f05ee6eb192ba70d391 been built? It's not in `/g/data/ik11/spack/0.21.2/modules/access-om3/0.x.0/linux-rocky8-cascadelake/access-om3/`

**Comment by aekiss** [comment]
PR now updated to use `/g/data/vk83/configurations` and `datamode=JRA55do` with updated exe. Test run seems ok.

@ezhilsabareesh8 can you have another look and approve if this look ok?

**Review by ezhilsabareesh8 — APPROVED** [review]
Thanks @aekiss, it looks good to me. It is running and the data mode is `JRA55do` in `atm.log`.

**Comment by anton-seaice** [comment]
!cherry-pick 3933627904916c7b08c54950abaf2abce0c23ad3..a5fd61b2c5b79556ef8a873f9f23f291796641b2 into dev-1deg_jra55do_ryf_wombatlite

**Comment by anton-seaice** [comment]
!cherry-pick 3933627904916c7b08c54950abaf2abce0c23ad3 db5e8e8c77f3a595ec0e9a2726b4a610f4e57c79 654dbd78088208812de94fea87a9d43cb194cefa 3e839234e6dd762161473b8b7625dbfd61bf6663 1707a792ecadc1a39df2cdf110ad95290bab51e8 a5fd61b2c5b79556ef8a873f9f23f291796641b2 into dev-1deg_jra55do_ryf_wombatlite

**Comment by anton-seaice** [comment]
!cherry-pick https://github.com/ACCESS-NRI/access-om3-configs/commit/3933627904916c7b08c54950abaf2abce0c23ad3 https://github.com/ACCESS-NRI/access-om3-configs/commit/db5e8e8c77f3a595ec0e9a2726b4a610f4e57c79 https://github.com/ACCESS-NRI/access-om3-configs/commit/654dbd78088208812de94fea87a9d43cb194cefa https://github.com/ACCESS-NRI/access-om3-configs/commit/3e839234e6dd762161473b8b7625dbfd61bf6663 https://github.com/ACCESS-NRI/access-om3-configs/commit/1707a792ecadc1a39df2cdf110ad95290bab51e8 https://github.com/ACCESS-NRI/access-om3-configs/commit/a5fd61b2c5b79556ef8a873f9f23f291796641b2 into dev-025deg_jra55do_ryf

**Comment by anton-seaice** [comment]
!cherry-pick 3933627904916c7b08c54950abaf2abce0c23ad3 db5e8e8c77f3a595ec0e9a2726b4a610f4e57c79 654dbd78088208812de94fea87a9d43cb194cefa 3e839234e6dd762161473b8b7625dbfd61bf6663 1707a792ecadc1a39df2cdf110ad95290bab51e8 a5fd61b2c5b79556ef8a873f9f23f291796641b2 into dev-025deg_jra55do_ryf

**Pull request merged**
