### PR TITLE
Remove unused channel config parameter

### PR DESCRIPTION
**Pull request by anton-seaice**
Unset Channel_config per https://github.com/COSIMA/access-om3/issues/233

### CODE REVIEW

**Comment by anton-seaice** [comment]
!test repro

**Comment by anton-seaice** [comment]
@minghangli-uni - can you review? We can merge this

**Review by minghangli-uni — APPROVED** [review]

**Comment by anton-seaice** [comment]
! cherry-pick 38c039f4b87e6394ff54adde1986686195bb12e3 into dev-1deg_jra55do_iaf

**Comment by anton-seaice** [comment]
!cherry-pick 38c039f4b87e6394ff54adde1986686195bb12e3 into dev-1deg_jra55do_iaf

**Comment by anton-seaice** [comment]
!cherry-pick 38c039f4b87e6394ff54adde1986686195bb12e3 into dev-1deg_jra55do_ryf_wombatlite

**Comment by anton-seaice** [comment]
!cherry-pick 38c039f4b87e6394ff54adde1986686195bb12e3 into dev-1deg_jra55do_ryf_wombatlite

**Pull request merged**
