### PR TITLE
fix JRA55do runoff remapping bug

### PR DESCRIPTION
**Pull request by aekiss**
closes https://github.com/COSIMA/access-om3/issues/208

### CODE REVIEW

**Comment by aekiss** [comment]
this will need to be cherry-picked into all other configs

**Comment by anton-seaice** [comment]
I guess we need the same change to https://github.com/COSIMA/om3-scripts/blob/main/data_stream_xml_generation/generate_xml_datm.py ?

**Comment by aekiss** [comment]
Ah yes, good point! @ezhilsabareesh8 do you have a spare moment to do that?

**Review by ezhilsabareesh8 — APPROVED** [review]
Thanks, @aekiss! This looks good to me, and it's running without any issues. I can change the [data_stream_xml_generation](https://github.com/COSIMA/om3-scripts/blob/main/data_stream_xml_generation) files to reflect these changes.

**Comment by dougiesquire** [comment]
Sorry to be a pain in the arse, but I don't think we want to get in the habit of making changes without updating the manifest. I understand they can make cherry-picking difficult, but they're an important part of the provenance.

**Review by dougiesquire — CHANGES_REQUESTED** [review]
Also, it would be best to regenerate the `datm.streams.xml` and `drof.streams.xml` using the new `generate_xml_*.py` in `om3-scripts` so that they have the correct provenance metadata

**Comment by aekiss** [comment]
Agreed @dougiesquire, I'd forgotten these files were script-generated so we should re-generate them (and while we're at it, fix https://github.com/COSIMA/om3-scripts/issues/27 and https://github.com/COSIMA/om3-scripts/issues/29).

Re. manifests, I think we should have one commit containing only the manifest changes, and another containing everything else. That way we can just cherry-pick the 2nd commit.

**Comment by dougiesquire** [comment]
> Agreed @dougiesquire, I'd forgotten these files were script-generated so we should re-generate them (and while we're at it, fix https://github.com/COSIMA/om3-scripts/issues/27 and https://github.com/COSIMA/om3-scripts/issues/29).

Sorry, I was rushing and I merged https://github.com/COSIMA/om3-scripts/pull/28 before seeing your new `om3-scripts` issues. I agree we should fix these both. @ezhilsabareesh8 could you please make these changes?

> Re. manifests, I think we should have one commit containing only the manifest changes, and another containing everything else. That way we can just cherry-pick the 2nd commit.

Sounds good to me

**Comment by dougiesquire** [comment]
@aekiss, `om3-scripts` has now been updated to fix the above issues (thanks to @ezhilsabareesh8). I've updated the version of `om3-scripts` at `/g/data/vk83/apps/om3-scripts`, so you could use that to generate the new stream files.

**Comment by aekiss** [comment]
Thanks @dougiesquire, I'm happy for somebody else to do that if you're waiting on it - I'm busy in a workshop tomorrow so might struggle to get to it.

**Comment by aekiss** [comment]
thanks Dougie

**Comment by aekiss** [comment]
Closing - PR replaced by https://github.com/ACCESS-NRI/access-om3-configs/pull/123

**Pull request closed without merging**
