### PR TITLE
set DIABATIC_FIRST to False by default.

### PR DESCRIPTION
**Pull request by minghangli-uni**
See https://github.com/COSIMA/access-om3/issues/137

### CODE REVIEW

**Comment by dougiesquire** [comment]
Thanks @minghangli-uni. @aekiss, do you think this requires any testing?

**Comment by minghangli-uni** [comment]
For a bit of background, DIABATIC_FIRST has to be False by default when the tracer timestep differs from the coupling timestep. See https://github.com/COSIMA/access-om3/issues/138#issuecomment-2209659553

**Review by aekiss — APPROVED** [review]
LGTM, thanks @minghangli-uni. This change will need to be made in all the other configs too.

**Comment by minghangli-uni** [comment]
Thanks @aekiss

**Comment by minghangli-uni** [comment]
!cherry-pick 3a5f47a into dev-1deg_jra55do_ryf dev-1deg_jra55do_iaf dev-1deg_jra55do_ryf_wombatlite

**Pull request merged**
